### ISSUE TITLE
upgrade ACME version

### ISSUE THREAD

**Issue by radomsak** [Parquery/revproxyry#9]
2019/12/03 00:20:19 http: TLS handshake error from 31.10.145.167:6456: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by lbrgt** [comment]
It seems that the revproxery binary in this repository isn't built with the latest version of crypto/acme/autocert which take into account the change from ACMEv1 to ACMEv2 (https://github.com/golang/go/issues/21081). Unfortunately, the new binary doesn't solve the error. We will investigate more next week.

**Comment by Sasha93** [comment]
revproxyry 1.0.7 bumped on Jan 14, 2020, solved the issue.
